version: '3'
services:
  client:
    build: ./client/
    ports:
      - "80:80"
    image: govindgiri2021/docker-compose-push-demo1:image1
  server:
    build: ./server/
    ports:
      - "8081:8081"
    image: govindgiri2021/docker-compose-push-demo2:image2
